### ISSUE TITLE
Svelte Vietnam Logo

### ISSUE THREAD

**Issue by vnphanquang** [sveltevietnam/sveltevietnam.dev#23]
## Context

A logo is essential to the site & community we are trying to build. It helps create a first impression and longterm recognition.

## Design

Design a logo for Svelte Vietnam with the following requirements, besides adhering to the context & objective discussed in [Project References]():

1. is minimal,
2. has ratio of 1x1,
3. has indication of Svelte,
4. has indication of Vietnam,
5. works for all themes and languages (single logo, no variation).

## Development

- [x] place in the new logo where applicable
- [x] setup favicon & necessary logo & icon in meta tags

## Community Building

- [x] Add new logo to:
  - [x] [Discord](https://discord.gg/Rtv2xwhz7d)
  - [x] [Twitter](https://twitter.com/sveltevietnam)
  - [x] [Github](https://github.com/sveltevietnam)
    - [x] organization profile
    - [x] [branding repo](https://github.com/sveltevietnam/branding)
    - [x] [sveltevietnam.dev repo](https://github.com/sveltevietnam/sveltevietnam.dev)
  - [x] [Facebook](https://facebook.com/sveltevietnam)
  - [ ] [Google Console](https://admin.google.com/u/1/ac/companyprofile/personalization)
  - [x] [Vercel](https://vercel.com/teams/sveltevietnam/settings)
  - [x] [Gravatar](https://en.gravatar.com/)
- [x] Scaffold & organize v1 & v2 logos into the [branding repo](https://github.com/sveltevietnam/branding)

Should discuss about create a custom banner/ profile photo for facebook & twitter?

**Comment by trongtran-t97** [comment]
- First logo check.
- Trong will continue logo edit and prepare website style.

**Comment by vnphanquang** [comment]
Updated with v2.1 to support better blending in dark background
![sveltevietnam-logo](https://user-images.githubusercontent.com/25895844/226912718-b584e91b-1034-49d6-bdc1-fc21935574cc.jpg)
