### ISSUE TITLE
Blogs

### ISSUE THREAD

**Issue by vnphanquang** [sveltevietnam/sveltevietnam.dev#96]
## Context

Currently, our content is seasonal (project call / showcases, events, jobs). We are missing content that:

- is frequent to keep the website alive & engaging, and
- can represent the voice of actual members in the Svelte Vietnam community, making things feel 'less commercial' and more at home for visitors.

Blog posts are probably the best kind of content for these purposes. It can help get people involved in the community and promote sharing.

The priority of this content should be above all accept for events.

Let's explore possibilities and ideas to design and implement blog pages.

## Inspirations

- https://github.blog/
- https://joshcollinsworth.com/blog
- https://www.figma.com/blog/
- https://kentcdodds.com/blog

```[tasklist]
### Setup & Design
- [x] Setup Archiecture
- [x] Setup guidelines and github issue templates for authors
- [x] High-fedility wireframe
- [x] Design
```

```[tasklist]
### Development
- [x] wireframe version
- [x] Add `blog` as a new domain for subscription
- [x] Apply application Typography styles to `@tailwindcss/typography`
- [ ] design version
- [x] Strategy for Code Blocks & Syntax Highlighting (https://github.com/sveltevietnam/sveltevietnam.dev/commit/02d09429bf411039affe5a1c9cdc8ce3f701d18c)
- [ ] https://github.com/sveltevietnam/sveltevietnam.dev/issues/188
- [ ] Strategy for image optimization
```

## Basic UI Structure

- `/blog` page: index page that lists all posts vertically; no pagination for now; ach list item shows:
  - title of blog
  - excerpt / quick description
  - profile picture and name of author. Name is optionally clickable and will link to author's page of choice
  - cover image, picked by the author, and fallback to a default, used for OG image as well.
- `/blog/[slug]` page: actual blog post; general layout should be the same with predefined general style for heading and spacing between blocks. But content should be free and can be anything. Consider not having the cover image too big at the top (hurt performance)

We have `vi` and `en`, so the blog content and blog metadata string properties should have two version, except for the slug of the post, which should have a format of `YYYYMMDDHHMMSS_slug`: timestamp when blog post is initiated, plus some text for quick identification.

## Tentative Architecture

Just like all existing content, we should avoid a database as much as possible, at least for the foreseeable future, because otherwise it would introduce too much complexity and maintenance effort. Let's keep everything static:

- blog content is just a hard-coded `+page.svelte`,
- blog metadata should be POJO with 2 version  for 2 `en` & `vi`.

### Directory Structure

```tree
sites/www/src/routes/[[lang]]/blog/
    |-- +page.svelte
    |-- [slug]
        |-- +page.svelte
        |-- +page.server.ts
        |-- _page
            |-- content.vi.svelte
            |-- content.en.svelte
            |-- meta.ts
            |-- content.ts
```

### Development Strategy

see https://github.com/sveltevietnam/sveltevietnam.dev/pull/103

Each blog post is a folder at `sites/www/src/routes/[[lang]]/blog/[slug]`, Blog post content goes in `_page/page.[lang].svelte` corresponding to the language. A blog post can be in one or both languages. Use `hygen` to automate the post creation process, things to do:

- [x] automatically load the correct lang based on URL
- [x] automatically render the h1 and cover image
- [x] automatically apply correct page metadata (meta, SEO tags)
- [x] apply sensible styling defaults, perhaps `@tailwindcss/typography`
- [x] adding to a global list constant, for rendering on the blog index (post listing) page

### Submitting a Blog Post Proposal

We should provide two ways to submit a proposal for blog post:

1. via Github issue (using templates). This is a no-code solution that is friendly and more accessible to everyone. Blog post is submitted in text & image formats (for example, a markdown / word doc file with some design concept in figma). After the content passes review, a maintainer will implement it via a linked PR.
2. via direct code. This is typically for developers or those who want to play around or have more controls over blog post. For example one might include interactive elements or data visualization. We should provide a technical document / guidelines for this, which is also reused for maintainers responsible for implementing blog post via (1).

### Translating a blog post

A post proposal can be in `vi`, `en`, or both. In the case where one of the two languages is not initially included, we should have a process for other contributors to help with translation. Ideas:

### Linking External 

Apart from writing posts in our site, we should also support linking to other sources. This is helpful for people that prefer other platform for writing, or already have some posts elsewhere.

- a notice section in the post page of original language that calls for translation help,
- a github issue tag that indicates a post needs translation,
- a dedicated channel on discord to notify and call for help.

## Recognition

We should have a system to recognize people that have contributed for this type of content in any form, especially original authors. For now, let's award via a custom role in discord, something like 'Writer' with a distinguished color.

**Comment by vnphanquang** [comment]
Github Issue templates implemented in https://github.com/sveltevietnam/sveltevietnam.dev/issues/105

**Comment by sorae42** [comment]
There's a Masonry layout library: https://github.com/janosh/svelte-bricks which should be suitable for the `/blog` page. I wonder if you like this layout too?

**Comment by vnphanquang** [comment]
@sorae42 thanks for the suggestion. We will go with a more traditional layout like one in https://github.blog. The first draft of the blog page is being actively worked on right now (https://github.com/sveltevietnam/sveltevietnam.dev/tree/feat/blog-first-draft). It'll be released soon and please feel free to give feedback then.

[Masonry](https://developer.mozilla.org/en-US/docs/Web/CSS/CSS_grid_layout/Masonry_layout) is good for quick rapid content in a flow like images, we will probably use that for event detail page to display photos.

**Comment by vnphanquang** [comment]
Blog seems stable so far. Closing for now. Revisit with more specific problem if any.
